# fly.toml app configuration file generated for ringed-crow on 2023-10-04T13:37:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ringed-crow"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
