version: 3

tasks:
  cache:
    cmd: bun install 

  dev:
    deps:
      - cache
    cmd: infisical run --env=dev --path=ringed-crow --secret-overriding -- bun run cmd/ringed-crow/dev.ts

  env:
    cmds:
      - infisical secrets --path=ringed-crow {{.CLI_ARGS}}

  img:
    cmds: 
      - docker build -t ringed-crow .
      - docker run --rm --env-file <(infisical export --env=dev --path=ringed-crow --format=dotenv) -p 8000:8000 ringed-crow