version: 3

tasks:
  cache:
    cmd: bun install 

  dev:
    deps:
      - cache
    cmd: bun run start

  img:
    cmds: 
      - docker build -t bun-elysia .
      - docker run --rm -p 8000:8000 bun-elysia